spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taifex?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: Asia/Taipei
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/templates,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
server:
  port: 8080
